build:
  # cache:
  #   # https://docs.gitlab.com/ee/ci/yaml/#cache
  #   key: 5.1.1-ubuntu
  #   # keep a distinct cache for each compiler version
  #   paths:
  #     - _opam
  script:
    - opam init -y && opam switch create --yes --no-install . 5.1.1
    - eval $(opam env)
    - opam remote add uptodate https://github.com/ocaml/opam-repository.git
    - opam install . --yes --depext-only
    - opam install . --deps-only --with-test --with-doc --yes
    - dune build
    - dune runtest
