variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  # cache:
  #   # https://docs.gitlab.com/ee/ci/yaml/#cache
  #   key: 5.1.1-ubuntu
  #   # keep a distinct cache for each compiler version
  #   paths:
  #     - _opam
  script:
    - opam init -y && opam switch create --yes --no-install . 5.1.1
    - eval $(opam env)
    - opam remote add uptodate https://github.com/ocaml/opam-repository.git
    - opam install -y vendor/instrumentation2 vendor/ECMA-SL .
    - dune build @install
    - dune runtest
