ARG BASE_OS="ubuntu:24.04"
FROM ${BASE_OS}

ENV BASE=/home/explodejs
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y wget curl git unzip python3 python3-pip ca-certificates gnupg libgmp-dev graphviz sudo neovim && \
    echo "/usr/local/bin" | bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)" && \
    pip install --break-system-packages --upgrade setuptools

# Install Node.js
RUN mkdir -p /etc/apt/keyrings \
    && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_21.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
    && apt update \
    && apt install nodejs -y

# Configure 'explodejs' user
RUN useradd -ms /bin/bash explodejs && \
    echo explodejs:explodejs | chpasswd && \
    cp /etc/sudoers /etc/sudoers.bak && \
    echo "explodejs ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "umask 000" >> ${BASE}/.bash_profile && \
    echo "source ${BASE}/.bash_profile" >> ${BASE}/.bashrc && \
    chown explodejs:explodejs ${BASE}/.bash_profile && \
    chown explodejs:explodejs ${BASE}/.bashrc

USER explodejs
WORKDIR /home/explodejs

# Copy fast and datasets submodules
RUN mkdir -p /home/explodejs/explode-js/fast
RUN mkdir -p /home/explodejs/explode-js/datasets

COPY --chown=explodejs:explodejs ./bench/fast /home/explodejs/explode-js/fast
COPY --chown=explodejs:explodejs ./bench/datasets /home/explodejs/explode-js/datasets

# Remove .git dirs
RUN rm -rf /home/explodejs/explode-js/fast/.git \
    && rm -rf /home/explodejs/explode-js/datasets/.git

COPY ./bench/run-fast.py /home/explodejs/explode-js
COPY ./bench/table_fast.py /home/explodejs/explode-js
COPY ./bench/table_fast_time.py /home/explodejs/explode-js

# Install 'fast'
RUN python3 -m pip config set global.break-system-packages true
RUN cd /home/explodejs/explode-js/fast && ./install.sh

ENV PYTHONPATH="/home/explodejs/explode-js/fast"
