<start> ::= <program>;

<program> ::= <statement> | <statement> <program>;

<statement> ::= <var_decl>
              | <assignment> ";"
              | <if_stmt>
              | <while_stmt>
              | <function_decl>
              | <expr> ";"
              | <block>;

<block> ::= "{" <program> "}" | "{" "}";

<var_decl> ::= "var " <id> " = " <expr> ";";

<assignment> ::= <lhs> " = " <expr>;

<lhs> ::= <id> | <property_lookup>;

<property_lookup> ::= <primary_expr> "." <id>;

<if_stmt> ::= "if (" <expr> ") " <statement>
            | "if (" <expr> ") " <statement> " else " <statement>;

<while_stmt> ::= "while (" <expr> ") " <statement>;

<function_decl> ::= "function " <id> "(" <params> ") " <block>;

<expr> ::= <assignment>
         | <call_expr>
         | <arrow_expr>
         | <binary_expr>
         | <primary_expr>;

<binary_expr> ::= <primary_expr> " " <op> " " <expr>;

<op> ::= "+" | "-" | "*" | "/" | "==" | "<" | ">";

<call_expr> ::= <primary_expr> "(" <args> ")";

<args> ::= "" | <arg_list>;
<arg_list> ::= <expr> | <expr> ", " <arg_list>;

<params> ::= "" | <param_list>;
<param_list> ::= <id> | <id> ", " <param_list>;

<arrow_expr> ::= "(" <params> ") => " <arrow_body>;
<arrow_body> ::= <expr> | <block>;

<primary_expr> ::= <id>
                 | <property_lookup>
                 | <literal>
                 | "(" <expr> ")";

<literal> ::= <number> | <string_lit>;

<id> ::= <letter> | <letter> <alnum>+;

<string_lit> ::= "\"" <chars> "\"";
<chars> ::= (<alnum> | " " | "!")*;

<number> ::= <digit>+;
<alnum> ::= <letter> | <digit>;

<letter> ::= [a-z] | [A-Z] | "_";
<digit> ::= [0-9];
