<start> ::= <program>;

<program> ::= <line> | <line> "\n" <program>;

<line> ::= <command_list> | <comment> | <command_list> " " <comment> | "";

<comment> ::= "#" <any_chars>;

<command_list> ::= <command> | <command> ";" <command_list> | <command> "|" <command_list>;

<command> ::= <simple_cmd> | <var_assign> | <subshell>;

<simple_cmd> ::= <word> | <word> " " <args>;

<args> ::= <arg> | <arg> " " <args>;

<arg> ::= <word> | <var_ref> | <redirection>;

<var_assign> ::= <id> "=" <word>;

<var_ref> ::= "$" <id> | "${" <id> "}";

<subshell> ::= "$(" <command_list> ")";

<redirection> ::= ">" <word> | ">>" <word> | "<" <word>;

<word> ::= <id>;

<id> ::= <letter> | <letter> <alnum>+;
<any_chars> ::= (<alnum> | " " | "!")*;

<alnum> ::= <letter> | [0-9];
<letter> ::= [a-z] | [A-Z] | "_";
