name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      # allow opam depext to yes package manager prompts
      OPAMCONFIRMLEVEL: unsafe-yes
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout Submodules
        run: |
          git submodule update --init vendor/graphjs vendor/ECMA-SL

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.3"

      - name: Install dependencies
        run: opam install -y . --deps-only --with-dev-setup

      - name: Run lint
        run: ./scripts/lint.sh

  build:
    needs: lint
    env:
      # allow opam depext to yes package manager prompts
      OPAMCONFIRMLEVEL: unsafe-yes
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout Submodules
        run: |
          git submodule update --init vendor/graphjs vendor/ECMA-SL

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3

      - name: Install dependencies
        run: opam install -y . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build @install

      - name: Test
        run: opam exec -- dune runtest -j 1
