name: Build

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    env:
      # allow opam depext to yes package manager prompts
      OPAMCONFIRMLEVEL: unsafe-yes
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout Submodules
        run: |
          git submodule update --init vendor/graphjs vendor/ECMA-SL

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3

      - name: Install dependencies
        run: |
          opam install -y . --deps-only --with-test
          opam install ocamlformat

      - name: Run lint
        run: ./scripts/lint.sh

      - name: Build
        run: opam exec -- dune build @install

      - name: Test
        run: opam exec -- dune runtest -j 1
