name: Build

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/formalsec/ocaml-5.4-z3
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }} # This key is used for the main repo and submodules
          submodules: true

      - name: Install dependencies
        run: opam install -y . --deps-only --with-test

      - name: Run lint
        run: ./scripts/lint.sh

      - name: Build
        run: dune build @install

      - name: Test
        run: dune runtest -j 1
